const textStyles = {

    Header:{
        H7:{
            fontSize:"16",
            lineHeight:"24",
            fontWeight:"medium",
        },
        H6:{
            fontSize:"20",
            lineHeight:"28",
            fontWeight:"medium",
        },
        H5:{
            fontSize:"24",
            lineHeight:"36",
            fontWeight:"medium",
        },
        H4:{
            fontSize:"32",
            lineHeight:"36",
            fontWeight:"bold",
        },
        H3:{
            fontSize:"32",
            lineHeight:"36",
            fontWeight:"regular",
        },
        H2:{
            fontSize:"36",
            lineHeight:"48",
            fontWeight:"regular",
        },
        H1:{
            fontSize:"48",
            lineHeight:"56",
            fontWeight:"regular",
        },
        H0:{
            fontSize:"64",
            lineHeight:"72",
            fontWeight:"light",
        }
    },
    Body:{
        b6Caption:{
            fontSize:"12",
            lineHeight:"16",
            fontWeight:"regular"
        },
        b5Overline:{
            fontSize:"12",
            lineHeight:"20",
            fontWeight:"medium"
        },
        b4Button:{
            fontSize:"14",
            lineHeight:"16",
            fontWeight:"medium"
        },
        b3:{
            fontSize:"14",
            lineHeight:"20",
            fontWeight:"regular"
        },
        b2:{
            fontSize:"16",
            lineHeight:"24",
            fontWeight:"regular"
        },
        b1:{
            fontSize:"20",
            lineHeight:"30",
            fontWeight:"regular"
        }
    }
   

}

export default textStyles;